spring:
  datasource:
    url: jdbc:mysql://localhost:3306/LoginService
    username: root
    password: 120512zxc@
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true
        format_sql: true
